application: hello-flask-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /$
  static_files: dist/index.html
  upload: dist/index\.html
  secure: always
# All other URLs map directly to their path in _site/.
- url: /
  static_dir: dist
  http_headers:
    Access-Control-Allow-Origin: "*"
  secure: always


libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

